[package]
name = "printpdf"
version = "0.4.1"
authors = ["Felix Schütt <felix.schuett@maps4print.com>"]
repository = "https://github.com/fschutt/printpdf"
homepage = "https://github.com/fschutt/printpdf"
license = "MIT"
readme = "README.md"
description = "Rust library for writing PDF files"
keywords = ["pdf", "gui", "graphics", "wkhtmltopdf"]
categories = ["gui"]
exclude = ["./assets/*", "./doc/*", "./examples/*"]
autoexamples = false

[dependencies]
lopdf = { version = "0.26", default-features = false, features = ["pom_parser"] }
owned_ttf_parser = "0.12"
time = { version = "0.2.11", default-features = false, features = ["std"] }
log = { version = "0.4.8", optional = true }
svg2pdf = { version = "0.1.0", optional = true }

[dependencies.image]
version = "0.23"
default-features = false
features = ["gif", "jpeg", "png", "pnm", "tiff", "bmp"]
optional = true

[features]
default = ["embedded_images"]
clippy = []
logging = ["log"]
embedded_images = ["image"]
ico = ["image/ico"]
tga = ["image/tga"]
hdr = ["image/hdr"]
jpeg_rayon = ["image/jpeg_rayon"]
dxt = ["image/dxt"]
dds = ["image/dds"]
webp = ["image/webp"]
less-optimization = []
svg = ["svg2pdf"]

[target.'cfg(all(target_arch="wasm32",target_os="unknown"))'.dependencies]
js-sys = "0.3.40"

[badges]
travis-ci = { repository = "fschutt/printpdf" }
appveyor = { repository = "fschutt/printpdf" }

[[example]]
name = "bookmark"
default-features = false
required-features = []

[[example]]
name = "circle"
default-features = false
required-features = []

[[example]]
name = "font"
default-features = false
required-features = []

[[example]]
name = "image"
default-features = false
required-features = ["embedded_images"]

[[example]]
name = "no_icc"
default-features = false
required-features = []

[[example]]
name = "page"
default-features = false
required-features = []

[[example]]
name = "shape"
default-features = false
required-features = []

[[example]]
name = "svg"
default-features = false
required-features = ["svg"]